cleavercode/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('', include('store.urls')),
    path('payment/', include('payment.urls')),
    path('order/', include('order.urls')),
    path('notification/', include('notification.urls')),
    path('dashboard/', include('dashboard.urls')),

]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/urls.py
from django.urls import path
from dashboard import views

app_name = 'dashboard'
urlpatterns = [
    path('index/', views.DashboardIndexView.as_view(), name='dashboard_index'),
    path('products/', views.ProductListView.as_view(), name='product_list'),
    path('product/add-new/', views.AddNewProduct.as_view(), name='add_new_product'),
    path('product/update/<slug:slug>/', views.ProductUpdateView.as_view(), name='product_update'),
    path('product/delete/<slug:slug>/', views.ProductDeleteView.as_view(), name='product_delete'),
    path('categories/', views.CategoryListView.as_view(), name='category'),
    path('categories/add-new/', views.AddNewCategory.as_view(), name='add_new_category'),
    path('categories/<int:pk>/', views.CategoryUpdateView.as_view(), name='category_update'),
    path('categories/delete/<int:pk>/', views.CategoryDeleteView.as_view(), name='category_delete'),
]

order/urls.py
from django.urls import path

from order import views

app_name = 'order'
urlpatterns = [
    path('add-to-cart/<int:pk>/', views.add_to_cart, name='add-to-cart'),
    path('cart-view/', views.cart_view, name='cart'),
    path('remove-item/<int:pk>/', views.remove_item_from_cart, name='remove-item'),
    path('increase-quantity/<int:pk>/', views.increase_cart, name='increase'),
    path('decrease-quantity/<int:pk>/', views.decrease_cart, name='decrease'),
]

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/views.py
import imp
from django.shortcuts import redirect, render

from django.views.generic import TemplateView, ListView
from django.views.generic.edit import DeleteView

from store.models import Category, Product
from store.forms import (
    ProductForm,
    CategoryForm
)


# this is for dashboard index
class DashboardIndexView(TemplateView):
    def get(self, request, *args, **kwargs):
        return render(request, 'dashboard/index.html')


    def post(self, request, *args, **kwargs):
        pass


# product view
class ProductListView(TemplateView):
    def get(self, request, *args, **kwargs):
        products = Product.objects.all().order_by('-id')
        context = {
            'products': products
        }
        return render(request, 'dashboard/product_list.html', context)


    def post(self, request, *args, **kwargs):
        pass


class AddNewProduct(TemplateView):
    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            if request.user.user_type == 'developer':
                form = ProductForm()
                context = {
                    'form': form
                }
                return render(request, 'dashboard/add_form.html', context)
            else:
                return redirect('store:index')
            
            return redirect('account:profile')
        else:
            return redirect('store:index')

    def post(self, request, *args, **kwargs):
        if request.user.user_type == 'developer':
            if request.method == 'post' or request.method == 'POST':
                form = ProductForm(request.POST, request.FILES)
                if form.is_valid():
                    product = form.save(commit=False)
                    slug = product.name.replace(' ', '-')
                    product.slug = slug.lower()
                    product.save()
                    return redirect('dashboard:product_list')

                    
            else:
                return redirect('store:index')
        else:
            return redirect('store:index')



class ProductUpdateView(TemplateView):
    def get(self, request, slug, *args, **kwargs):
        product = Product.objects.get(slug=slug)
        form = ProductForm(instance=product)
        context = {
            'form': form
        }
        return render(request, 'dashboard/add_form.html', context)

    def post(self, request, slug, *args, **kwargs):
        if request.user.user_type == 'developer':
            if request.method == 'post' or request.method == 'POST':
                product_ins = Product.objects.get(slug=slug)
                form = ProductForm(request.POST, request.FILES, instance=product_ins)
                if form.is_valid():
                    product = form.save(commit=False)
                    slug = product.name.replace(' ', '-')
                    product.slug = slug.lower()
                    product.save()
                    return redirect('dashboard:product_list')

                    
            else:
                return redirect('store:index')
        else:
            return redirect('store:index')



class ProductDeleteView(TemplateView):
    def get(self, request, slug, *args, **kwargs):
        product = Product.objects.get(slug=slug)
        product.delete()
        return redirect('dashboard:product_list')




# category view
class CategoryListView(ListView):
    model = Category
    template_name = 'dashboard/category_list.html'
    context_object_name = 'categories'


class AddNewCategory(TemplateView):
    def get(self, request, *args):
        if request.user.user_type == 'developer':
            form = CategoryForm()
            context = {
                'form': form
            }
            return render(request, 'dashboard/add_form.html', context)
        else:
            return redirect('store:index')

    def post(self, request, *args, **kwargs):
        if request.user.user_type == 'developer':
            if request.method == 'post' or request.method == 'POST':
                form = CategoryForm(request.POST, request.FILES)
                if form.is_valid():
                    form.save()
                    return redirect('dashboard:category')

                    
            else:
                return redirect('store:index')
        else:
            return redirect('store:index')



class CategoryUpdateView(TemplateView):
    def get(self, request, pk, *args, **kwargs):
        category = Category.objects.get(id=pk)
        form = CategoryForm(instance=category)
        context = {
            'form': form
        }
        return render(request, 'dashboard/add_form.html', context)

    def post(self, request, pk, *args, **kwargs):
        if request.user.user_type == 'developer':
            if request.method == 'post' or request.method == 'POST':
                category = Category.objects.get(id=pk)
                form = CategoryForm(request.POST, request.FILES, instance=category)
                if form.is_valid():
                    form.save()
                    return redirect('dashboard:category')
            else:
                return redirect('store:index')
        else:
            return redirect('store:index')


class CategoryDeleteView(TemplateView):
    def get(self, request, pk, *args, **kwargs):
        category = Category.objects.get(id=pk)
        category.delete()
        return redirect('dashboard:category')

templates/dashboard/add_form.html
{% extends 'dashboard/base.html' %}

{% block body %}


<!--  BEGIN MAIN CONTAINER  -->
    <div class="main-container sidebar-closed sbar-open" id="container">

        <div class="overlay"></div>
        <div class="search-overlay"></div>

        
        {% include 'dashboard/sidebar.html' %}

        <!--  BEGIN CONTENT AREA  -->
        <div id="content" class="main-content">
            <div class="container">

                <div class="container">
                    <div class="row layout-top-spacing">
                        <div id="basic" class="col-lg-12 layout-spacing">
                            <div class="statbox widget box box-shadow">
                                <div class="widget-header">
                                    <div class="row">
                                        <div class="col-xl-12 col-md-12 col-sm-12 col-12">
                                            <h4>Input Text</h4>
                                        </div>                 
                                    </div>
                                </div>
                                <div class="widget-content widget-content-area">

                                    <div class="row">
                                        <div class="col-lg-12 col-12 mx-auto">
                                            <form method="post" enctype="multipart/form-data">
                                                <div class="form-group">
                                                    {% csrf_token %}
                                                    {{ form.as_p }}
                                                    
                                                    <input type="submit" name="txt" class="mt-4 btn btn-primary">
                                                </div>
                                            </form>
                                        </div>                                        
                                    </div>

                                </div>
                            </div>
                        </div>

                        
                    </div>

                </div>
            </div>
        </div>
        <!--  END CONTENT AREA  -->
    </div>
 
    {% endblock body %}

templates/dashboard/category_list.html
{% extends 'dashboard/base.html' %}

{% block body %}


<!--  BEGIN MAIN CONTAINER  -->
    <div class="main-container sidebar-closed sbar-open" id="container">

        <div class="overlay"></div>
        <div class="search-overlay"></div>

        
        {% include 'dashboard/sidebar.html' %}

        <!--  BEGIN CONTENT AREA  -->
        <div id="content" class="main-content">
            <div class="layout-px-spacing">
                <div class="row" id="cancel-row">
                
                    <div class="col-xl-12 col-lg-12 col-sm-12 layout-top-spacing layout-spacing">
                        <div class="widget-content widget-content-area br-6">
                            <a class="btn btn-primary" href={% url 'dashboard:add_new_category' %}>Add New Category</a>
                            
                            <table id="invoice-list" class="table table-hover" style="width:100%">
                                <thead>
                                    <tr>
                                        <th class="checkbox-column"> Record no. </th>
                                        <th>Name</th>
                                        <th>Parent</th>
                                        <th>Image</th>
                                        <th>Created</th>
                                        <th>Actions</th>
                                    </tr>
                                </thead>
                                <tbody>

                                {% for category in categories %}
                                    
                                    <tr>
                                        <td class="checkbox-column"> {{category.id}} </td>
                                        
                                        <td>
                                            <div class="d-flex">
                                                <p class="align-self-center mb-0 user-name"> {{category.name}} </p>
                                            </div>
                                        </td>
                                        <td><span class="inv-email"> {{category.parent}}</span></td>
                                        <td><span class="inv-date"> ${{category.image}} </span></td>
                                        <td><span class="inv-amount">${{category.created}}</span></td>
                                        <td>
                                            <div class="dropdown">
                                                <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-more-horizontal"><circle cx="12" cy="12" r="1"></circle><circle cx="19" cy="12" r="1"></circle><circle cx="5" cy="12" r="1"></circle></svg>
                                                </a>
                                                <div class="dropdown-menu" aria-labelledby="dropdownMenuLink2">
                                                    <a class="dropdown-item action-edit" href={% url 'dashboard:category_update' category.pk %}><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-edit-3"><path d="M12 20h9"></path><path d="M16.5 3.5a2.121 2.121 0 0 1 3 3L7 19l-4 1 1-4L16.5 3.5z"></path></svg>Edit</a>
                                                    <a class="dropdown-item action-delete" href={% url 'dashboard:category_delete' category.pk %}><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-trash"><polyline points="3 6 5 6 21 6"></polyline><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"></path></svg>Delete</a>
                                                </div>
                                            </div>
                                        </td>
                                    </tr>

                                {% endfor %}
                                    

                                    
                                </tbody>
                            </table>
                        </div>
                    </div>

                </div>
            </div>
        </div>
        <!--  END CONTENT AREA  -->
    </div>

    
{% endblock body %}

templates/dashboard/product_list.html
{% extends 'dashboard/base.html' %}

{% block body %}


<!--  BEGIN MAIN CONTAINER  -->
    <div class="main-container sidebar-closed sbar-open" id="container">

        <div class="overlay"></div>
        <div class="search-overlay"></div>

        
        {% include 'dashboard/sidebar.html' %}

        <!--  BEGIN CONTENT AREA  -->
        <div id="content" class="main-content">
            <div class="layout-px-spacing">
                <div class="row" id="cancel-row">
                
                    <div class="col-xl-12 col-lg-12 col-sm-12 layout-top-spacing layout-spacing">
                        <div class="widget-content widget-content-area br-6">
                            <a class="btn btn-primary" href={% url 'dashboard:add_new_product' %}>Add New Product</a>
                            
                            <table id="invoice-list" class="table table-hover" style="width:100%">
                                <thead>
                                    <tr>
                                        <th class="checkbox-column"> Record no. </th>
                                        <th>Name</th>
                                        <th>Category</th>
                                        <th>Price</th>
                                        <th>Old Price</th>
                                        <th>Status</th>
                                        <th>Actions</th>
                                    </tr>
                                </thead>
                                <tbody>

                                {% for product in products %}
                                    
                                    <tr>
                                        <td class="checkbox-column"> {{product.id}} </td>
                                        
                                        <td>
                                            <div class="d-flex">
                                                <p class="align-self-center mb-0 user-name"> {{product.name}} </p>
                                            </div>
                                        </td>
                                        <td><span class="inv-email"> {{product.category}}</span></td>
                                        <td><span class="inv-date"> ${{product.price}} </span></td>
                                        <td><span class="inv-amount">${{product.old_price}}</span></td>
                                        <td><span class="badge badge-danger inv-status">{{product.is_stock}}</span></td>
                                        <td>
                                            <div class="dropdown">
                                                <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-more-horizontal"><circle cx="12" cy="12" r="1"></circle><circle cx="19" cy="12" r="1"></circle><circle cx="5" cy="12" r="1"></circle></svg>
                                                </a>
                                                <div class="dropdown-menu" aria-labelledby="dropdownMenuLink2">
                                                    <a class="dropdown-item action-edit" href={% url 'dashboard:product_update' product.slug %}><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-edit-3"><path d="M12 20h9"></path><path d="M16.5 3.5a2.121 2.121 0 0 1 3 3L7 19l-4 1 1-4L16.5 3.5z"></path></svg>Edit</a>
                                                    <a class="dropdown-item action-delete" href={% url 'dashboard:product_delete' product.slug %}><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-trash"><polyline points="3 6 5 6 21 6"></polyline><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"></path></svg>Delete</a>
                                                </div>
                                            </div>
                                        </td>
                                    </tr>

                                {% endfor %}
                                    

                                    
                                </tbody>
                            </table>
                        </div>
                    </div>

                </div>
            </div>
        </div>
        <!--  END CONTENT AREA  -->
    </div>

    
{% endblock body %}

templates/dashboard/sidebar.html
<!--  BEGIN SIDEBAR  -->
<div class="sidebar-wrapper sidebar-theme">
            
    <nav id="sidebar">

        <ul class="navbar-nav theme-brand flex-row  text-center">
            <li class="nav-item theme-logo">
                <a href="#">
                    {% if request.user.is_authenticated %}
                        <img src="{{ request.user.profile.image.url }}" class="navbar-logo" alt="logo">
                    {% else %}
                        <img src="/static/user_profile/assets/img/90x90.jpg" class="navbar-logo" alt="logo">
                    {% endif %}
                </a>
            </li>
            <li class="nav-item theme-text">
                <a href="#" class="nav-link"> CLEVERANGE </a>
            </li>
        </ul>

        <ul class="list-unstyled menu-categories" id="accordionExample">
            <li class="menu active">
                <a href="#dashboard" data-toggle="collapse" aria-expanded="true" class="dropdown-toggle">
                    <div class="">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-home"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path><polyline points="9 22 9 12 15 12 15 22"></polyline></svg>
                        <span>Dashboard</span>
                    </div>
                    <div>
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-chevron-right"><polyline points="9 18 15 12 9 6"></polyline></svg>
                    </div>
                </a>
                <ul class="collapse submenu recent-submenu mini-recent-submenu list-unstyled show" id="dashboard" data-parent="#accordionExample">
                    <li class="active">
                        <a href="#"> General </a>
                    </li>
                    <li>
                        <a href="#"> Index </a>
                    </li>
                    
                </ul>
            </li>

            <li class="menu">
                <a href="#components" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
                    <div class="">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-box"><path d="M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z"></path><polyline points="3.27 6.96 12 12.01 20.73 6.96"></polyline><line x1="12" y1="22.08" x2="12" y2="12"></line></svg>
                        <span>Courses</span>
                    </div>
                    <div>
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-chevron-right"><polyline points="9 18 15 12 9 6"></polyline></svg>
                    </div>
                </a>
                <ul class="collapse submenu list-unstyled" id="components" data-parent="#accordionExample">
                

                    <li>
                        <a href="#"> My Courses </a>
                    </li>


                    <li>
                        <a href="#"> All Courses  </a>
                    </li>
                    
                </ul>
            </li>


            <li class="menu menu-heading">
                <div class="heading"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-minus"><line x1="5" y1="12" x2="19" y2="12"></line></svg><span>Features</span></div>
            </li>

            <li class="menu">
                <a href="#" aria-expanded="false" class="dropdown-toggle">
                    <div class="">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-grid-fill" viewBox="0 0 16 16">
                            <path d="M1 2.5A1.5 1.5 0 0 1 2.5 1h3A1.5 1.5 0 0 1 7 2.5v3A1.5 1.5 0 0 1 5.5 7h-3A1.5 1.5 0 0 1 1 5.5v-3zm8 0A1.5 1.5 0 0 1 10.5 1h3A1.5 1.5 0 0 1 15 2.5v3A1.5 1.5 0 0 1 13.5 7h-3A1.5 1.5 0 0 1 9 5.5v-3zm-8 8A1.5 1.5 0 0 1 2.5 9h3A1.5 1.5 0 0 1 7 10.5v3A1.5 1.5 0 0 1 5.5 15h-3A1.5 1.5 0 0 1 1 13.5v-3zm8 0A1.5 1.5 0 0 1 10.5 9h3a1.5 1.5 0 0 1 1.5 1.5v3a1.5 1.5 0 0 1-1.5 1.5h-3A1.5 1.5 0 0 1 9 13.5v-3z"/>
                          </svg>
                        <span>Join Live Class</span>
                    </div>
                </a>
            </li>

            <li class="menu">
                <a href="#" aria-expanded="false" class="dropdown-toggle">
                    <div class="">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-edit"><path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"></path><path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"></path></svg>
                        <span>Todo List</span>
                    </div>
                </a>
            </li>

            <li class="menu">
                <a href="apps_notes.html" aria-expanded="false" class="dropdown-toggle">
                    <div class="">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file-text"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline points="14 2 14 8 20 8"></polyline><line x1="16" y1="13" x2="8" y2="13"></line><line x1="16" y1="17" x2="8" y2="17"></line><polyline points="10 9 9 9 8 9"></polyline></svg>
                        <span>Notes</span>
                    </div>
                </a>
            </li>

            

            

            <li class="menu menu-heading">
                <div class="heading"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-minus"><line x1="5" y1="12" x2="19" y2="12"></line></svg><span>Cleverange</span></div>
            </li>


            <li class="menu">
                <a href="#" aria-expanded="false" class="dropdown-toggle">
                    <div class="">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-airplay"><path d="M5 17H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2h-1"></path><polygon points="12 15 17 21 7 21 12 15"></polygon></svg>
                        <span>Packages</span>
                    </div>
                </a>
            </li>


            <li class="menu">
                <a href="form_validation.html" aria-expanded="false" class="dropdown-toggle">
                    <div class="">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-target"><circle cx="12" cy="12" r="10"></circle><circle cx="12" cy="12" r="6"></circle><circle cx="12" cy="12" r="2"></circle></svg>
                        <span>Contact Us</span>
                    </div>
                </a>
            </li>

            

        </ul>
        
    </nav>

</div>
<!--  END SIDEBAR  -->